### ISSUE TITLE
Formats which should handle input hash case changes in some manner (fixing or rejecting)

### ISSUE THREAD

**Issue by jfoug** [magnumripper/JohnTheRipper#1742]
Ok, after adding test type #4 (true generic), ,I get these problems (some need white listed, not all are bugs).

$ ../run/john -test-full=1 | grep -v PASS
Will run 8 OpenMP threads

- [x] *FP* Testing: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]... (8xOMP) FAILED (split() is only casing sometimes (#4))
- [x] Testing: chap, iSCSI CHAP authentication [MD5 32/64]... (8xOMP) FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))
- [x] Testing: EPI, EPiServer SID [SHA1 32/64]... (8xOMP) FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))
- [x] Testing: openssl-enc, OpenSSL "enc" encryption [32/64]... FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))
- [x] Testing: PuTTY, Private Key [SHA1/AES 32/64]... (8xOMP) FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))
- [x] Testing: rar, RAR3 (4 characters) [SHA1 128/128 AVX 4x AES]... (8xOMP) FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))
- [x] Testing: wbb3, WoltLab BB3 [SHA1 32/64]... (8xOMP) FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))

Device 0: Cedar [ATI Radeon HD 5450]
- [x] Testing: rar-opencl, RAR3 (length 5) [SHA1 OpenCL AES]... (8xOMP) FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))
- [x] Testing: lotus5-opencl, Lotus Notes/Domino 5 [OpenCL]... FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))
- [x] *FP* Testing: bcrypt-opencl ("$2a$05", 32 iterations) [Blowfish OpenCL]... FAILED (split() is only casing sometimes (#4))

- [x] Testing: keychain-opencl, Mac OS X Keychain [PBKDF2-SHA1 OpenCL 3DES]... (8xOMP) FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))
- [x] Testing: keyring-opencl, GNOME Keyring [SHA256 OpenCL AES]... (8xOMP) FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))
- [x] Testing: ODF-opencl [SHA1 OpenCL Blowfish]... (8xOMP) FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))
- [x] Testing: ODF-AES-opencl [SHA256 OpenCL AES]... (8xOMP) FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))
- [x] Testing: strip-opencl, STRIP Password Manager [PBKDF2-SHA1 OpenCL]... (8xOMP) FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))
- [x] Testing: sxc-opencl, StarOffice .sxc [PBKDF2-SHA1 OpenCL Blowfish]... (8xOMP) FAILED (should not set FMT_SPLIT_UNIFIES_CASE (#4))

These are the only ones I see that are left:

(*FP*) Testing: AFS, Kerberos AFS [DES 24/32 4K]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))
Testing: dynamic_40 [sha1($s.pad20($p)) (net-sha1) 32/32]... FAILED (cmp_all(1))
Testing: dynamic_1016 [md5($p.$s) (long salt) 32/32]... FAILED (cmp_all(1))
Testing: dynamic=md5($p) [32/32]... FAILED (split() case, or valid() should fail)
(*FP*) Testing: krb5-18, Kerberos 5 db etype 18 [PBKDF2-SHA1 32/32 AES]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))
(*FP*) Testing: cq, ClearQuest [CQWeb]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))
(*FP*) Testing: hdaa, HTTP Digest access authentication [MD5 32/32]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))
(*FP*) Testing: Blackberry-ES10 (101x) [SHA-512 32/32 OpenSSL]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))
(*FP*) Testing: LUKS [PBKDF2-SHA1 32/32]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))
Testing: MongoDB, system / network [MD5 32/32]... FAILED (should unify cases in split() and set FMT_SPLIT_UNIFIES_CASE (#3))
Testing: mssql, MS SQL [SHA1 32/32]... FAILED (split() case, or valid() should fail)
Testing: mssql05, MS SQL 2005 [SHA1 32/32]... FAILED (split() case, or valid() should fail)
Testing: mssql12, MS SQL 2012/2014 [SHA512 32/32 OpenSSL]... FAILED (split() case, or valid() should fail)

All new 'test-3' that are failures are false-positive.

There is a lot of discussion and code in this PR:  https://github.com/magnumripper/JohnTheRipper/pull/1741

(WHITE LISTED)  This one STILL needs fixed.
- [x] dynamic=md5($p) 32/32 (MD5_body) [dynamic_6000]... FAILED (split() case, or valid() should fail)  

- [x] Testing: dynamic_40 [sha1($s.pad20($p)) (net-sha1) 32/32]... FAILED (cmp_all(1))
- [x] Testing: dynamic_1016 [md5($p.$s) (long salt) 32/32]... FAILED (cmp_all(1))

These 3 were somehow missed. I listed them as fixed, but when I pulled the github, they were not fixed.  Now they are.
- [x] Testing: mssql, MS SQL [SHA1 32/32]... FAILED (split() case, or valid() should fail)
- [x] Testing: mssql05, MS SQL 2005 [SHA1 32/32]... FAILED (split() case, or valid() should fail)
- [x] Testing: mssql12, MS SQL 2012/2014 [SHA512 32/32 OpenSSL]... FAILED (split() case, or valid() should fail)

- [x] OpenBSD-SoftRAID (8192 iterations) [PBKDF2-SHA1 32/32]... FAILED (split() case, or valid() should fail)
- [x] PBKDF2-HMAC-MD5 [PBKDF2-MD5 32/32]... FAILED (split() case, or valid() should fail)
- [x] Oracle12C [PBKDF2-SHA512 32/32]... FAILED (split() case, or valid() should fail)
- [x] has-160 [HAS-160 32/32]... FAILED (split() case, or valid() should fail)
- [x] pomelo [POMELO 32/32]... FAILED (split() case, or valid() should fail)
- [x] tc_aes_xts, TrueCrypt AES256_XTS [SHA512 32/32 /RIPEMD160/WHIRLPOOL]... FAILED (split() case, or valid() should fail)
- [x] tc_ripemd160, TrueCrypt AES256_XTS [RIPEMD160 32/32]... FAILED (split() case, or valid() should fail)
- [x] tc_sha512, TrueCrypt AES256_XTS [SHA512 32/32]... FAILED (split() case, or valid() should fail)
- [x] tc_whirlpool, TrueCrypt AES256_XTS [WHIRLPOOL 32/32]... FAILED (split() case, or valid() should fail)
- [x] PFX, PKCS12 (.pfx, .p12) [32/32]... FAILED (split() case, or valid() should fail)
- [x] SSH (one 2048-bit RSA and one 1024-bit DSA key) [RSA/DSA 32/32]... FAILED (split() case, or valid() should fail)
- [x] rsvp, HMAC-MD5 / HMAC-SHA1, RSVP, IS-IS [MD5 32/32]... FAILED (split() case, or valid() should fail)
- [x] eigrp, EIGRP MD5 / HMAC-SHA-256 authentication [MD5 32/32]... FAILED (split() case, or valid() should fail)
- [x] Mozilla, Mozilla key3.db [SHA1 3DES 32/32]... FAILED (split() case, or valid() should fail)
- [x] vtp, "MD5 based authentication" VTP [MD5 32/32]... FAILED (split() case, or valid() should fail)
- [x] dmd5, DIGEST-MD5 C/R [MD5 32/32]... FAILED (split() case, or valid() should fail)
- [x] EPI, EPiServer SID [SHA1 32/32]... FAILED (split() case, or valid() should fail)
- [x] ipb2, Invision Power Board 2.x [MD5 32/32]... FAILED (split() case, or valid() should fail)
- [x] krb4, Kerberos v4 TGT [DES 32/32]... FAILED (split() case, or valid() should fail)
- [x] krb5, Kerberos v5 TGT [3DES 32/32]... FAILED (split() case, or valid() should fail)
- [x] KeePass [SHA256 AES 32/32 OpenSSL]... FAILED (split() case, or valid() should fail)
- [x] skey, S/Key [MD4/MD5/SHA1/RMD160 32/32]... FAILED (split() case, or valid() should fail)
- [x] agilekeychain, 1Password Agile Keychain [PBKDF2-SHA1 AES 32/32]... FAILED (split() case, or valid() should fail)
- [x] Blockchain, My Wallet (x10) [PBKDF2-SHA1 AES 32/32]... FAILED (split() case, or valid() should fail)
- [x] chap, iSCSI CHAP authentication [MD5 32/32]... FAILED (split() case, or valid() should fail)
- [x] cloudkeychain, 1Password Cloud Keychain [PBKDF2-SHA512 32/32]... FAILED (split() case, or valid() should fail)
- [x] dmg, Apple DMG [PBKDF2-SHA1 3DES/AES 32/32]... FAILED (split() case, or valid() should fail)
- [x] eCryptfs (65536x) [SHA512 32/32 OpenSSL]... FAILED (split() case, or valid() should fail)
- [x] EFS [PBKDF2-SHA1-efs-variant 3DES 32/32]... FAILED (split() case, or valid() should fail)
- [x] EncFS [PBKDF2-SHA1 AES/Blowfish 32/32]... FAILED (split() case, or valid() should fail)
- [x] fde, Android FDE [PBKDF2-SHA1 SHA256/AES 32/32]... FAILED (split() case, or valid() should fail)
- [x] gpg, OpenPGP / GnuPG Secret Key [32/32]... FAILED (split() case, or valid() should fail)
- [x] keychain, Mac OS X Keychain [PBKDF2-SHA1 3DES 32/32]... FAILED (split() case, or valid() should fail)
- [x] keyring, GNOME Keyring [SHA256 AES 32/32 OpenSSL]... FAILED (split() case, or valid() should fail)
- [x] keystore, Java KeyStore [SHA1 32/32]... FAILED (split() case, or valid() should fail)
- [x] kwallet, KDE KWallet [SHA1 32/32]... FAILED (split() case, or valid() should fail)
- [x] lotus5, Lotus Notes/Domino 5 [8/32 X2]... FAILED (split() case, or valid() should fail)
- [x] lotus85, Lotus Notes/Domino 8.5 [8/32]... FAILED (split() case, or valid() should fail)
- [x] MD2 [MD2 32/32]... FAILED (split() case, or valid() should fail)
- [x] MongoDB, system / network [MD5 32/32]... FAILED (split() case, or valid() should fail)
- [x] nk, Nuked-Klan CMS [SHA1 MD5 32/32]... FAILED (split() case, or valid() should fail)
- [x] o5logon, Oracle O5LOGON protocol [SHA1 AES 32/32]... FAILED (split() case, or valid() should fail)
- [x] ODF [SHA1/SHA256 BF/AES 32/32 OpenSSL]... FAILED (split() case, or valid() should fail)
- [x] Office, 2007/2010/2013 [SHA1 32/32 / SHA512 32/32 OpenSSL AES]... FAILED (split() case, or valid() should fail)
- [x] oldoffice, MS Office <= 2003 [MD5/SHA1 RC4 32/32]... FAILED (split() case, or valid() should fail)
- [x] openssl-enc, OpenSSL "enc" encryption [32/32]... FAILED (split() case, or valid() should fail)
- [x] oracle11, Oracle 11g [SHA1 32/32]... FAILED (split() case, or valid() should fail)
- [x] Panama [Panama 32/32]... FAILED (split() case, or valid() should fail)
- [x] PDF [MD5 SHA2 RC4/AES 32/32]... FAILED (split() case, or valid() should fail)
- [x] PKZIP [32/32]... FAILED (split() case, or valid() should fail)
- [x] postgres, PostgreSQL C/R [MD5 32/32]... FAILED (split() case, or valid() should fail)
- [x] PST, custom CRC-32 [32/32]... FAILED (split() case, or valid() should fail)
- [x] PuTTY, Private Key [SHA1/AES 32/32]... FAILED (split() case, or valid() should fail)
- [x] RACF [DES 32/32]... FAILED (split() case, or valid() should fail)
- [x] RAdmin, v2.x [MD5 32/32]... FAILED (split() case, or valid() should fail)
- [x] rar, RAR3 (4 characters) [SHA1 AES 32/32]... FAILED (split() case, or valid() should fail)
- [x] RAR5 [PBKDF2-SHA256 32/32 OpenSSL]... FAILED (split() case, or valid() should fail)
- [x] 7z, 7-Zip (512K iterations) [SHA256 32/32 AES]... FAILED (split() case, or valid() should fail)
- [x] Snefru-128 [32/32]... FAILED (split() case, or valid() should fail)
- [x] Snefru-256 [32/32]... FAILED (split() case, or valid() should fail)
- [x] SSH-ng [RSA/DSA 32/32]... FAILED (split() case, or valid() should fail)
- [x] STRIP, Password Manager [PBKDF2-SHA1 32/32]... FAILED (split() case, or valid() should fail)
- [x] sxc, StarOffice .sxc [SHA1 Blowfish 32/32]... FAILED (split() case, or valid() should fail)
- [x] Sybase-PROP [salted FEAL-8 32/32]... FAILED (split() case, or valid() should fail)
- [x] VNC [DES 32/32]... FAILED (split() case, or valid() should fail)
- [x] wbb3, WoltLab BB3 [SHA1 32/32]... FAILED (split() case, or valid() should fail)

This hash was found after hex salt 'smashing' was added'
- [x] Testing: netntlm, NTLMv1 C/R [MD4 DES (ESS MD5) 32/32]... FAILED (split() case, or valid() should fail)

Format problems found only with https://github.com/loverszhaokai/JohnTheRipper/commit/01abf3ff176d371441b979fb750c885d3c91f0d9 and moved from #1752 to here.

- [x] Blackberry-ES10
- [x] cq
- [x] hdaa   (false positive!)
- [x] krb5-18    (false positive!)
- [x] lp
- [x] lotus5
- [x] LUKS    (false positive!)
- [x] mdc2
- [x] PBKDF2-HMAC-MD4

**Comment by jfoug** [comment]
NOTE, just casing the binary hash may not be enough. If there are other hex encoded areas within the hash, then each of those areas either have to be properly cased.

One other method is to draw a line in the sand, and say case of the hex fields must either be UP or low.  Then within valid() we reject hashes with the wrong case.

The best way is to do this with a case changing split. However, if the hashes are 100% specified (such as a specific server, or coming from one of the *2john generators), then using valid() to reject input hashes that are cased improperly should be perfectly acceptable.

**Comment by jfoug** [comment]
Here was nuked clan.  and the test showing that it was fixed.  Without this fix, this input file with 5 hashes each having 3 different casing layouts, you would run john once and get 5, then run it again and get 5 then run it again, and get 5 hashes, then run it again and all hashes were found.

After the fix, you run it one time it finds 5 hashes and is done.

```
$ ../run/john in
Using default input encoding: UTF-8
Loaded 15 password hashes with 5 different salts (nk, Nuked-Klan CMS [SHA1 MD5 32/64])
Press 'q' or Ctrl-C to abort, almost any other key for status
test3            (test3)
test3            (test3)
test3            (test3)
thatsworking     (thatsworking)
thatsworking     (thatsworking)
thatsworking     (thatsworking)
test1            (test1)
test1            (test1)
test1            (test1)
password         (password)
password         (password)
password         (password)
openwall         (openwall)
openwall         (openwall)
openwall         (openwall)
15g 0:00:00:00 DONE 1/3 (2015-09-10 14:17) 2500g/s 2166p/s 3833c/s 11500C/s openwall..password
Use the "--show" option to display all of the cracked passwords reliably
Session completed

$ ../run/john in
Using default input encoding: UTF-8
Loaded 15 password hashes with 5 different salts (nk, Nuked-Klan CMS [SHA1 MD5 32/64])
No password hashes left to crack (see FAQ)

$ cat ../run/john.pot
$nk$*796b7375666d7545695032413769443977644132*#4aec90bd9a930faaa42a0d7d40056132e:test3
$nk$*7a317a71794339586c434d50506b6e4356626a67*#b62a615f605c2fd520edde76577d30f90:thatsworking
$nk$*503476424c5362476f36463630796a6e6c656165*#2f27c20e65b88b76c913115cdec3d9a18:test1
$nk$*379637b4fcde21b2c5fbc9a00af505e997443267*#5c20384512ee36590f5f0ab38a46c6ced:password
$nk$*379637b4fcde21b2c5fbc9a00af505e997443267*#17737d3661312121d5ae7d5c6156c0298:openwall

```

**Comment by jfoug** [comment]
NOTE, any format that mangles the binary (such as raw hashes which now 'early exit' modify the running binary value), will not be found using my search method.  An example of a problem hash that was not found is AFS  (as documented in and around http://www.openwall.com/lists/john-dev/2015/09/11/7 )  There may be other raw formats which should fix dupe case problems, but which my code can not find.   ALL of the raw hashes should be audited for this bug.  It is easy to do.  Simply get the raw 'working' hashes using the -list=format-tests   Then duplicate all hashes 3 or 4 times in the 'input' file, and make random case changes to these new lines.   Then if you crack them with john, and re-run john again against the 'should be' cracked file, and it starts cracking again, THEN the bug is present on that format. If you crack them all, then run again and john says 'all cracked', then things are running correctly.

**Comment by jfoug** [comment]
Actually, it might not be a bad idea to make a issue thread (this one is fine), where we have a checklist of EVERY format.  Then when we validate the format is correct, OR we find a problem and fix it, we then check it off.  Yes, that is a LOT of things to check off, but it may be the only way to document that we have ALL of them done. ONCE we get them all done, we can make some pretty deep tests to flush out problems, and leave that in the formats.c file self test (-full or normal, either way is fine).  Then we can help ensure that as new formats are written, the original developer is 'forced' into writing it correctly from the start, to not have this bug.

**Comment by jfoug** [comment]
8f21e31

That adds the -test-full enhancement that found many of these files. NOTE, there are still some files which have hex encoding that do not properly split/case.  we need to audit formats and find these.

Most of the raw formats can not be auto found any more, since they have last round reversal logic in them, thus binary() does not return the 'same' value as stored in the hash.

We probably should add code to find all 'pure' hex-like strings of 28, 32, 40, 48, 64, bytes long (etc) (and longer ones of 'known' hex hash size), and mangle those to 'test'.  NOTING that some of those may end up needing a white list.

**Comment by jfoug** [comment]
At this time, only dynamic= fails with salt/case bug, and there are 2 'failures' for other reasons in dynamic.  But other than that, ALL formats 'are' working properly for -test-full code!

**Comment by jfoug** [comment]
Closing.  100% of the formats that are currently 'listed' have been fixed, with 1 being whitelisted (for now).

**Comment by jfoug** [comment]
Note, test #4 're-found' a problem in CHAP.   So each test has been getting better and better, lol.
