### ISSUE TITLE
Single mode fixes

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#3594]
See #3467, #2425 

- [x] Add a `--single-retest-guess=BOOL` option that overrides whatever is in john.conf.
- [x] Add a john.conf limit for levels of recursion with single-retest-guess (eg. 10000). See [#2425](
https://github.com/magnumripper/JohnTheRipper/issues/2425#issuecomment-453853364)
- [x] Add a free when cracking ends because all cracked, see [#2425](https://github.com/magnumripper/JohnTheRipper/issues/2425#issuecomment-453855398)
- [x] [Postpone (or duplicate) the warning/notice](https://github.com/magnumripper/JohnTheRipper/issues/2425#issuecomment-454890010)

**Comment by jfoug** [comment]
I would like to add here, that we should NOT have a commented out line
```
# Un-commenting this stops Single mode from re-testing guessed plaintexts
# with all other salts.
#SingleRetestGuessed = N
```

But should be
```
# Change to 'N' to stop Single mode from re-testing guessed plaintexts
# with all other salts.
SingleRetestGuessed = Y
```

These commented out lines in the Options section should all be looked at, and (if possible), uncommented with proper default setting set, and the comment changed.  This will allow the option to show up if the ``` --list=parameters:Options ```

Yes, a bit off-topic here, but I wanted this to be talked about. If it is deemed 'a good thing', then we can easily create a issue to hang it on.

**Comment by magnumripper** [comment]
Good idea. Please open an issue for reviewing and fixing all such cases.

**Comment by magnumripper** [comment]
I will now look at this: https://github.com/magnumripper/JohnTheRipper/issues/2425#issuecomment-454890010
